accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signupUser, name='signup'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
]

findspot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mapping.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

mapping/urls.py
from django.urls import path
from . import views

app_name = 'mapping'
urlpatterns = [
    path('', views.index, name='homepage'),
    path('buildings/', views.showBuilding, name='tobuilding'),
    path('bureaux/', views.showBureau, name='tobureau'),
    path('locals/', views.showLocal, name='tolocal'),
    path('spaces/', views.showSpace, name='tospace'),
]

accounts/models.py
from django.db import models

# Create your models here.

mapping/models.py
from django.db import models

class AddressType(models.Model):
    label = models.CharField(max_length=40, verbose_name=('Nom de la catégorie'))
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name = ("Catégorie d'adresse")
        verbose_name_plural = ("Catégories d'adresses")

    def __str__(self):
        return self.label

class Address(models.Model):
    latitude = models.FloatField()
    longitude = models.FloatField()
    interest = models.BooleanField(default=False, verbose_name=("Définir point d'interêt"))
    description = models.TextField(blank = True, null=True, verbose_name=("Description de l'adresse"))
    adtype = models.ForeignKey(AddressType, verbose_name=("Catégorie de l'adresse"), on_delete=models.CASCADE)

class Building(Address):
    name = models.CharField(max_length=100, verbose_name=('Nom du bâtiment/bureau'))  
    localnum = models.IntegerField(verbose_name=('Nombre de locaux'),null=True, blank=True, default=0)
    burnum = models.IntegerField(verbose_name=('Nombre de bureaux/directions'),null=True, blank=True, default=0)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Bâtiments")
        verbose_name_plural = ("Bâtiments")

    def __str__(self):
        return self.name

class Bureau(Address):
    name = models.CharField(max_length=100, verbose_name=("Nom du Bureau/Direction"))  
    burbuilding = models.ForeignKey(Building, verbose_name=("Son bâtiment"),null=True, blank=True, default='Aucun', on_delete=models.CASCADE)
    hallnum = models.IntegerField(verbose_name=('Nombre d\'office'),null=True, blank=True, default=0)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Bureau/Direction")
        verbose_name_plural = ("Bureaux/Directions")

    def __str__(self):
        return self.name

class Office(Address):
    name = models.CharField(max_length=100, verbose_name=("Nom de l'office")) 
    officebur = models.ForeignKey(Building, verbose_name=("Son bureau"), on_delete=models.CASCADE) 
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Office")
        verbose_name_plural = ("Offices")

    def __str__(self):
        return self.name

class Local(Address):
    name = models.CharField(max_length=100, verbose_name=("Nom du Local"))  
    burbuilding = models.ForeignKey(Building, verbose_name=("Son bâtiment"), null=True, blank=True, default='Aucun', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Local/Salle")
        verbose_name_plural = ("Locaux/Salles")

    def __str__(self):
        return self.name

class Space(Address):
    name = models.CharField(max_length=100, verbose_name=("Nom de l'espace"))  
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = ("Espace")
        verbose_name_plural = ("Espaces")

    def __str__(self):
        return self.name

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms




class UserCustomerForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
    username = forms.CharField(label="Nom d'utilisateur", widget=forms.TextInput(attrs={'placeholder': 'Nom d\'utilisateur'}))
    email = forms.EmailField(label="Adresse mail",widget=forms.EmailInput(attrs={'placeholder': 'Adresse mail'}))

    password1 = forms.CharField(label="Mot de passe",
                              widget=forms.PasswordInput(attrs={'placeholder': 'Entrer le mot de passe'}))
    password2 = forms.CharField(label="Confirmer le mot de passe",
                              widget=forms.PasswordInput(attrs={'placeholder': 'Confirmer le mot de passe'}))

accounts/views.py
from django.shortcuts import render,redirect
#from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import UserCustomerForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('mapping:homepage')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('mapping:homepage') 
        else:
            messages.info(request, 'Identifiant ou mot de passe incorrect')
    
    #formular = AuthenticationForm()          
    context = {
        'page':page,
        #'form':formular,
    }

    return render(request, 'accounts/login_signup.html', context)

def signupUser(request):
    if request.method == 'POST':
        formular = UserCustomerForm(request.POST)
        if formular.is_valid():
            user = formular.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user) # Login user after creation
            return redirect('mapping:homepage') # Homepage is the name given to the home url
        else:
            messages.error(request, 'Une erreur durant la création')
    
    else:
        formular = UserCustomerForm()

    context = {
        'form': formular,
        }

    return render(request, 'accounts/login_signup.html', context)

def logoutUser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('mapping:homepage')

    return render(request, 'accounts/logout.html')

mapping/views.py
from django.shortcuts import render
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Building, Bureau, Local, Office, Space

def index(request):
    page = 'home'
    search_term = request.GET.get('searchbar')
    buildings = Building.objects.all()
    bureaux = Bureau.objects.all()
    offices = Office.objects.all()
    locals_ = Local.objects.all()
    spaces = Space.objects.all()

    if search_term :
        search_result  = Building.objects.filter(
            Q(name__icontains=search_term)
        )
    else:
        search_result = []
   
    #maps_center = Space.objects.get(name='centre du campus')

    context = {
        'page':page,
        'buildings':buildings,
        'bureaux':bureaux,
        'offices':offices,
        'locals':locals_,
        'spaces':spaces,
        'search_result':search_result,
        'search_term':search_term,
        #'center':maps_center,
    }
    return render(request, 'mapping/home.html', context)

def showBuilding(request):
    page = 'building'
    buildings = Building.objects.all()
    context = {'buildings':buildings,'page':page,}

    return render(request, 'mapping/home.html', context)

def showBureau(request):
    page = 'bureau'
    bureaux = Bureau.objects.all()
    context = {'page':page,'bureaux':bureaux}

    return render(request, 'mapping/home.html', context)

def showLocal(request):
    page = 'local'
    locals_ = Local.objects.all()
    context = {'page':page,'locals':locals_}

    return render(request, 'mapping/home.html', context)

def showSpace(request):
    page = 'space'
    spaces = Space.objects.all()
    context = {'page':page,'spaces':spaces}

    return render(request, 'mapping/home.html', context)

@login_required(login_url='login')
def showInterestPoint(request):
    page = 'interestpoint'
    buildings = Building.objects.filter(interest=True)
    offices = Office.objects.filter(interest=True)
    spaces = Space.objects.filter(interest=True)

    context = {
        'page':page,
        'buldings':buildings,
        'offices':offices,
        'spaces':spaces
    }

    
#def display
"""@login_required(login_url='login')
def addEvent(request):
    pass"""

accounts/templates/accounts/login_signup.html
{% extends 'main.html' %}
{% block content %}


    {% for message in messages %}
        <p>{{message}}</p>
    {% endfor %}
    <div class="auth_container">
        <div class="auth_aside">
            <span>Bienvenue sur Findspot Maps UPN</span>
            <small>Naviguer sur le campus en toute sécurité</small>
        </div>
        {% if page == 'login' %}
        <div id='auth_div'>
            <span id="app_title">Findspot Maps</span>
            <span id="auth_subtitle">Connectez-vous a votre compte utilisateur</span>
            
            <form method="POST" action="">
                {% csrf_token %}
                <input type="text" name="username" id="" placeholder="Nom d'utilisateur">
                <input type="password" name="password" id="" placeholder="Mot de passe">
                <input type="submit" value="Se Connecter" id="connexion_btn"/>
            </form>
            <div class="auth_bottom"> 
                <p>Vous n'avez pas de compte ?</p>
                <a href="{% url 'accounts:signup' %}">Créer un compte</a>
            </div>
        </div>

        {% else %}
        <div id="auth_div">
            <span id="app_title">Findspot Maps</span>
            <span id="auth_subtitle">Rejoignez la plateforme de localisation fiable</span>
            <form method="POST" action="" id="usercreation">
                {% csrf_token %}
                {% for field in form %}     
                    {{field}}
                {% endfor %}    
                <input type="submit" value="Créer" id="connexion_btn"/>
            </form>
            <div class="auth_bottom"> 
                <p>Vous avez déjà un compte ?</p>
                <a href="{% url 'accounts:login' %}">Se connecter</a>
            </div>

        </div>
        {% endif %}
    </div>
    
{% endblock content %}

accounts/templates/accounts/logout.html
{% extends 'main.html' %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <p>Comptez-vous vous deconnecter ?</p>
    <a href="{{request.META.HTTP_REFERER}}">Retour</a>
    <input type="submit" value="Confirmer"/>
</form>

{% endblock content %}

mapping/templates/mapping/building_comp.html
{% load static %}

{% for item in buildings %}
map.on('load', () => {
    var iconElement = document.createElement('div');
    iconElement.className = 'marker1';

    var subtitle = document.createElement('h4');
    subtitle.className = 'subtitle'
    subtitle.textContent = '{{ item.name|safe }}';

    iconElement.appendChild(subtitle);

    new mapboxgl.Marker(iconElement)
        .setLngLat([{{ item.longitude|safe }}, {{ item.latitude|safe }}])
        .addTo(map);
            
});
{% endfor %}




    

mapping/templates/mapping/bureau_comp.html
{% load static %}
{% for item in bureaux %}


map.on('load', () => {
    var iconElement = document.createElement('div');
    iconElement.className = 'marker2';

    var subtitle = document.createElement('h4');
    subtitle.className = 'subtitle'
    subtitle.textContent = '{{ item.name|safe }}';

    iconElement.appendChild(subtitle);

    new mapboxgl.Marker(iconElement)
        .setLngLat([{{ item.longitude|safe }}, {{ item.latitude|safe }}])
        .addTo(map);
            
});
{% endfor %}

mapping/templates/mapping/home.html
{% extends "main.html" %}
{% load static %}
{% block content %}

<header>
    <nav>
        <ul>
            <li><a href="{% url "mapping:homepage" %}" class="main_title">Findspot UPN</a></li>
        </ul>

        {% if user.is_authenticated %}
        <ul class="buttons">
            <li>
                <a href="{% url "mapping:homepage" %}" class="user_activate">
                    {{user.username}} est connecté
                </a>
            </li>|
            <li><a href="{% url "accounts:logout" %}">Déconnexion</a></li>
        </ul>
    
        {% else %}
        <ul class="buttons">
            <li><a href="{% url "accounts:signup" %}">Inscription</a></li>|
            <li><a href="{% url "accounts:login" %}">Connexion</a></li>
        </ul>
        
        {% endif %}
    </nav>
</header>

<section>
    <div class="mainview">
        <div>
            <a href="{% url "mapping:homepage" %}" id="activate">Accueil</a>
        </div>
        <div>
            <a href="{% url "mapping:tobuilding" %}">Bâtiments</a>
        </div>
        <div>
            <a href="{% url "mapping:tobureau" %}">Bureaux / Directions</a>
        </div>
        <div>
            <a href="{% url "mapping:tolocal" %}">Locaux</a>
        </div>
        <div>
            <a href="{% url "mapping:tospace" %}">Lieux / Espaces</a>
        </div>

        {% if user.is_authenticated %}
        <div><a href="">Points d'intêret</a></div>
        <div><a href="">Historique</a></div> 
        {% endif %}

    </div>

    <div class="controlview">
        {% if user.is_authenticated %}
        <form action="" method="get">
            <div id="lil_menu">
                <input type="search" name="searchbar" id="search_place" placeholder="Trouver un lieu">
                
                <button id="location_btn">Moi</button>
                <select name="" id="location_choice">
                    <option value="">Choisissez une location</option>
                    <option value="moi">Moi</option>
                    {% for element in buildings %}
                    <option value="{{element}}">{{ element }}</option>
                    {% endfor %}
                </select>
    
                <select name="" id="destination_choice">
                    <option value="">Choisissez une destination</option>
                    <option value="moi">Moi</option>
                    {% for element in buildings %}
                    <option value="{{element}}">{{ element }}</option>
                    {% endfor %}
                </select>
    
                <button id="navigation_btn">Navigation</button>
            </div>
        </form>

        
        
        <div id="lil_menu2">
            <input id="satellite-streets-v12" type="radio" name="rtoggle" value="satellite">
            <!-- See a list of Mapbox-hosted public styles at -->
            <!-- https://docs.mapbox.com/api/maps/styles/#mapbox-styles -->
            <label for="satellite-streets-v12">Satellite</label>
            <input id="dark-v11" type="radio" name="rtoggle" value="dark">
            <label for="dark-v11">Sombre</label>
            <input id="streets-v12" type="radio" name="rtoggle" value="streets" checked="checked">
            <label for="streets-v12">Rues</label>
            <input id="outdoors-v12" type="radio" name="rtoggle" value="outdoors">
            <label for="outdoors-v12">Exterieurs</label>
        </div>
        {% endif %}
        
        <!--div id="markerpanel">
            <ul>
                <li>Afficher la description</li>
                <li>Ajouter point d'interet</li>
            </ul>
        </div-->

        <div id="mapview"></div>
    </div>
</section>
<footer>
    Cette application est concu par Insight Invaders | Tous drois réservés
</footer>

<script>

    mapboxgl.accessToken = 'pk.eyJ1IjoibmF0ZS1pbnNpZ2h0IiwiYSI6ImNscHd3dm9wNjBoamIyaW51cTAwdGl0eWwifQ.PYpsdnx1xuR1ZcJyCAN35Q';
    var map = new mapboxgl.Map({
        container: 'mapview',
        style: 'mapbox://styles/mapbox/streets-v12', 
        center: [15.25784, -4.40545], // 
        zoom: 18,
        //minZoom: 16,
        attributionControl: false
    });


    var bounds = [
        [15.254346633583879,-4.4079479442164455], // Coordonnées du coin sud-ouest de la zone
        [15.261302677174427,-4.400099066015827]  // Coordonnées du coin nord-est de la zone
    ];
    map.setMaxBounds(bounds)

        
    // Change map's style
    const layerList = document.getElementById("lil_menu2"); // Retrieve elements from lil-menu2 div
    const inputs = layerList.getElementsByTagName('input'); // 

    for (const input of inputs) {
        input.onclick = (layer) => {
            const layerId = layer.target.id;
            map.setStyle('mapbox://styles/mapbox/' + layerId);
        };
    }

    const button = document.getElementById("yourButtonId"); // Replace with your button's ID
    const geolocateButton = document.getElementById('location_btn');
    geolocateButton.addEventListener('click', function(){
            // User location
        navigator.geolocation.getCurrentPosition(successLocation, errorLocation, {
            enableHighAccuracy: true
        });

        function successLocation(position) {
            const { coords } = position;
            const { latitude, longitude } = coords;

            new mapboxgl.Marker()
                .setLngLat([longitude, latitude])
                .addTo(map);

            watchUserLocation();
        }

        function errorLocation() {
            console.log('Unable to retrieve your location');
        }

        function watchUserLocation() {
            navigator.geolocation.watchPosition((position) => {
                const { coords } = position;
                const { latitude, longitude } = coords;

                map.setCenter([longitude, latitude]);

                const marker = new mapboxgl.Marker()
                    .setLngLat([longitude, latitude])
                    .addTo(map);
            });
        }
    });

    {% if search_result %}
        {% for item in search_result %}
        new mapboxgl.Marker({color : 'red'})
        .setLngLat([{{ item.longitude|safe }}, {{ item.latitude|safe }}])
        .addTo(map);
        map.setCenter([{{ item.longitude|safe }}, {{ item.latitude|safe }}])
        
        {% endfor %}
    {% endif %}

    {% if page == "home" %}
        {% include "mapping/home_comp.html" %}

    {% elif page == "building" %}
        {% include "mapping/building_comp.html" %}

    {% elif page == "bureau" %}
        {% include "mapping/bureau_comp.html" %}

    {% elif page == "local" %}
        {% include "mapping/local_comp.html" %}

    {% elif page == "space" %}
        {% include "mapping/space_comp.html" %}
        
    {% endif %}

</script>

{% endblock content %}

mapping/templates/mapping/home_comp.html
{% load static %}

{% for item in buildings %}

map.on('load', () => {

    var popup = new mapboxgl.Popup({
        offset: 25,
        closeButton: true,
        closeOnClick: true,
      }).setHTML('<li>Afficher la description</li>'); 

    var iconElement = document.createElement('div');
    iconElement.className = 'marker1';

    var subtitle = document.createElement('h4');
    subtitle.className = 'subtitle'
    subtitle.textContent = '{{ item.name|safe }}';

    iconElement.appendChild(subtitle);

    new mapboxgl.Marker(iconElement)
        .setLngLat([{{ item.longitude|safe }}, {{ item.latitude|safe }}])
        .setPopup(popup)
        .addTo(map);
            
});
{% endfor %}

{% for item in bureaux %}
map.on('load', () => {
    var iconElement = document.createElement('div');
    iconElement.className = 'marker2';

    var subtitle = document.createElement('h4');
    subtitle.className = 'subtitle'
    subtitle.textContent = '{{ item.name|safe }}';

    iconElement.appendChild(subtitle);

    new mapboxgl.Marker(iconElement)
        .setLngLat([{{ item.longitude|safe }}, {{ item.latitude|safe }}])
        .addTo(map);
});
{% endfor %}

{% for item in locals %}
map.on('load', () => {
    var iconElement = document.createElement('div');
    iconElement.className = 'marker3';

    var subtitle = document.createElement('h4');
    subtitle.className = 'subtitle'
    subtitle.textContent = '{{ item.name|safe }}';

    iconElement.appendChild(subtitle);

    new mapboxgl.Marker(iconElement)
        .setLngLat([{{ item.longitude|safe }}, {{ item.latitude|safe }}])
        .addTo(map);
            
});
{% endfor %}

{% for item in spaces %}
map.on('load', () => {
    var iconElement = document.createElement('div');
    iconElement.className = 'marker4';

    var subtitle = document.createElement('h4');
    subtitle.className = 'subtitle'
    subtitle.textContent = '{{ item.name|safe }}';

    iconElement.appendChild(subtitle);

    new mapboxgl.Marker(iconElement)
        .setLngLat([{{ item.longitude|safe }}, {{ item.latitude|safe }}])
        .addTo(map);
            
});
{% endfor %}

mapping/templates/mapping/local_comp.html
{% load static %}
{% for item in locals %}

map.on('load', () => {
    var iconElement = document.createElement('div');
    iconElement.className = 'marker3';

    var subtitle = document.createElement('h4');
    subtitle.className = 'subtitle'
    subtitle.textContent = '{{ item.name|safe }}';

    iconElement.appendChild(subtitle);

    new mapboxgl.Marker(iconElement)
        .setLngLat([{{ item.longitude|safe }}, {{ item.latitude|safe }}])
        .addTo(map);
            
});

{% endfor %}

mapping/templates/mapping/space_comp.html
{% load static %}

{% for item in spaces %}
map.on('load', () => {
    var iconElement = document.createElement('div');
    iconElement.className = 'marker4';

    var subtitle = document.createElement('h4');
    subtitle.className = 'subtitle'
    subtitle.textContent = '{{ item.name|safe }}';

    iconElement.appendChild(subtitle);

    new mapboxgl.Marker(iconElement)
        .setLngLat([{{ item.longitude|safe }}, {{ item.latitude|safe }}])
        .addTo(map);
            
});
{% endfor %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- load the mapbox native js and css -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.9.1/mapbox-gl.css' rel='stylesheet'/>

    
    <link rel="stylesheet" href={%static 'css/style.css'%}>

    <title>Findspot Maps | UPN</title>

</head>
<body>
    {% block content %}

    {% endblock content %}

</body>
</html>